/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface GridDescription {}
  interface GridDescriptionAttributes extends StencilHTMLAttributes {}

  interface GridImage {
    'src': string;
  }
  interface GridImageAttributes extends StencilHTMLAttributes {
    'src'?: string;
  }

  interface GridRoot {
    'gridClass': boolean;
  }
  interface GridRootAttributes extends StencilHTMLAttributes {
    'gridClass'?: boolean;
  }

  interface GridTitle {}
  interface GridTitleAttributes extends StencilHTMLAttributes {}

  interface GridToggle {}
  interface GridToggleAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AppRoot': Components.AppRoot;
    'GridDescription': Components.GridDescription;
    'GridImage': Components.GridImage;
    'GridRoot': Components.GridRoot;
    'GridTitle': Components.GridTitle;
    'GridToggle': Components.GridToggle;
  }

  interface StencilIntrinsicElements {
    'app-root': Components.AppRootAttributes;
    'grid-description': Components.GridDescriptionAttributes;
    'grid-image': Components.GridImageAttributes;
    'grid-root': Components.GridRootAttributes;
    'grid-title': Components.GridTitleAttributes;
    'grid-toggle': Components.GridToggleAttributes;
  }


  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLGridDescriptionElement extends Components.GridDescription, HTMLStencilElement {}
  var HTMLGridDescriptionElement: {
    prototype: HTMLGridDescriptionElement;
    new (): HTMLGridDescriptionElement;
  };

  interface HTMLGridImageElement extends Components.GridImage, HTMLStencilElement {}
  var HTMLGridImageElement: {
    prototype: HTMLGridImageElement;
    new (): HTMLGridImageElement;
  };

  interface HTMLGridRootElement extends Components.GridRoot, HTMLStencilElement {}
  var HTMLGridRootElement: {
    prototype: HTMLGridRootElement;
    new (): HTMLGridRootElement;
  };

  interface HTMLGridTitleElement extends Components.GridTitle, HTMLStencilElement {}
  var HTMLGridTitleElement: {
    prototype: HTMLGridTitleElement;
    new (): HTMLGridTitleElement;
  };

  interface HTMLGridToggleElement extends Components.GridToggle, HTMLStencilElement {}
  var HTMLGridToggleElement: {
    prototype: HTMLGridToggleElement;
    new (): HTMLGridToggleElement;
  };

  interface HTMLElementTagNameMap {
    'app-root': HTMLAppRootElement
    'grid-description': HTMLGridDescriptionElement
    'grid-image': HTMLGridImageElement
    'grid-root': HTMLGridRootElement
    'grid-title': HTMLGridTitleElement
    'grid-toggle': HTMLGridToggleElement
  }

  interface ElementTagNameMap {
    'app-root': HTMLAppRootElement;
    'grid-description': HTMLGridDescriptionElement;
    'grid-image': HTMLGridImageElement;
    'grid-root': HTMLGridRootElement;
    'grid-title': HTMLGridTitleElement;
    'grid-toggle': HTMLGridToggleElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
